version: 2
  
orbs:
  python: circleci/python:3.6.4

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: tests/requirements.txt
          pkg-manager: pip
      - run:
          command: tests/runtests.py
          name: Run ninjs unit tests using Python lxml

workflows:
  main:
    jobs:
      - build-and-test
