version: 2
  
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r tests/requirements.txt
      - run:
          name: Run NewsML-G2 unit tests using Python lxml
          command: |
            tests/runtests.py

