version: 2
  
orbs:
  python: circleci/python:3.7.7

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: tests/requirements.txt
          pkg-manager: pip
      - run:
          command: tests/runtests.py
          name: Run NewsML-G2 unit tests using Python lxml
